name:                git-helper
version:             0.1.1.5
github:              "killmen0w/git-helper"
license:             BSD3
author:              "Maksim Golubev"
maintainer:          "maksim.golubev72@gmail.com"
copyright:           "2018 Maksim Golubev"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Git

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/killmen0w/git-helper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - git-utils >= 0.1.3.0
  - process
  - text
  - cmdargs

executables:
  gith:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-helper
    - git-utils >= 0.1.3.0
    - process
    - cmdargs
    - mtl
    - time
    - text
    - containers
    - attoparsec
    - regex-tdfa

tests:
  gith-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
